### PR TITLE
Record with table name

### PR DESCRIPTION
**Pull request by robinborst95**
Record now has a table name in it.

### CODE REVIEW

**Comment by grootstyr** [comment]
I think a better strategy would be to have the user specify a new name for the result of a multi table operation, and then have the controller keep track of the tables and their names. Single table operation's do not require any naming design.

**Comment by robinborst95** [comment]
A problem with that solution is that in a combined table with records from the StatSensor and the Website, there cannot be decided whether a Record is a StatSensor measurement or a website entry. With a table name in it, a Record now knows whether it is a StatSensor or Website record.

**Comment by Unset** [comment]
Test worked. When using codes it is a lot easier now to detect where the record came from (as apposed to checking for non-empty columns)

**Comment by paulbakker65** [comment]
Looks good to me, everything was tested and worked as intended.

**Pull request merged**
